### ISSUE TITLE
ReferenceError : regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by OmkarK45** [altafino/react-webpack-5-tailwind-2#10]
Hey there, I'm facing this error while using async-await in my application.

Reproduction Repo : https://github.com/OmkarK45/jit-repo (App.js file)

I believe it's a problem with babel

**Comment by OmkarK45** [comment]
Update : So I followed this answer -> https://github.com/babel/babel/issues/9849#issuecomment-619554829

And async-await is working again.

**Comment by stefanwuthrich** [comment]
tks for reporting and fix @OmkarK45
