### ISSUE TITLE
App not working in IE 11

### ISSUE THREAD

**Issue by Anandks1993** [altafino/react-webpack-5-tailwind-2#19]
Hi, Thanks for this great boilerplate. It really helps me to kick start a react project.

I tried opening the app in IE 11 but getting `SCRIPT1002: Syntax error`  this error. 

Please let me know how to overcome this problem.

**Comment by stefanwuthrich** [comment]
Thanks for reporting, but sorry, but IE 11 is something I really do not more consider to support 2021
But you can probably fix it going through this (adding react-app-polyfill/ie11)

https://create-react-app.dev/docs/supported-browsers-features/

**Comment by Anandks1993** [comment]
@stefanwuthrich Thank you for your reply. I will check the link you have shared. Meanwhile is there anything that we can do in babel to fix this?
