### ISSUE TITLE
Windows machine 'NODE_ENV' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by Sensiblemnd** [altafino/react-webpack-5-tailwind-2#20]
When doing a yarn build

'NODE_ENV' is not recognized as an internal or external command,

**Comment by Sensiblemnd** [comment]
Fix:
yarn add -D cross-env
in package json 

"build": "cross-env  NODE_ENV=production webpack --config config/webpack.prod.js",
    "build-staging": "cross-env NODE_ENV=production webpack --config config/webpack.stag.js",

**Comment by stefanwuthrich** [comment]
tks @Sensiblemnd 
If you want, you can add a pull request or tell me to do
