### ISSUE TITLE
Help: Upgrade to Tailwind 3!

### ISSUE THREAD

**Issue by wmonecke** [altafino/react-webpack-5-tailwind-2#26]
Has anyone been able to upgrade to Tailwind 3 yet? I am getting stuck and have little clue on what to do next.

**Comment by schmanat** [comment]
Hi @wmonecke 

To get TailwindCSS 3 working you have to do some configuration changes. 

1. Open the packages.json and remove the follwing lines:
-  ```"tailwindcss": "^2.2.7"``` (Line 20)
- ```"node-sass": "^6.0.1",``` (Line 85)

2. Install the new packages
- ```npm install --save sass``` ([node-sass is deprecated](https://sass-lang.com/blog/libsass-is-deprecated) 
- ```npm install -D tailwindcss@latest``` (Tailwind will be installed as dev dependency) 

3. Update tailwind.config.js
```js
module.exports = {
  content: ['./src/**/*.js'],
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
``` 
(replace purge with content, and remove darkMode)

After this changes tailwind 3 works (for me :)).

If you have use some features of Tailwind please read the official [upgrade Guide of Tailwind](https://tailwindcss.com/docs/upgrade-guide)

**Comment by wmonecke** [comment]
@schmanat Thanks for the help! I do get the bundler working but the css is not being applied, even after clearing cache.

**Comment by wmonecke** [comment]
@schmanat Nevermind! You also need to install `sass` as a devDependency! Thank you so much!
