### ISSUE TITLE
Add eslint-plugin-react-hooks

### ISSUE THREAD

**Issue by tdemarest** [altafino/react-webpack-5-tailwind-2#6]
With the popularity of Hooks as of 16.8.0 it would be nice if the eslint-plugin-react-hooks plugin was added to ESlint. More info and the two main rules are here: https://reactjs.org/docs/hooks-rules.html#eslint-plugin

**Comment by stefanwuthrich** [comment]
thank you for your input @tdemarest 
I added the plugin.
