### ISSUE TITLE
Problems using Tailwind JIT

### ISSUE THREAD

**Issue by OmkarK45** [altafino/react-webpack-5-tailwind-2#9]
Hi there, thank you for this boilerplate. However, when I replace contents of `postcss.config.js` to this ` // postcss.config.js
  module.exports = {
    plugins: {
      '@tailwindcss/jit': {},
      autoprefixer: {},
    }
  }`
  
  I have to restart webserver in order to load new changes in styles.
  Please let me know what I'm doing wrong

**Comment by OmkarK45** [comment]
Update on this: 
So I was suggested not to use scss extension for index style file. That being paired with NODE_ENV=development has fixed the issue for me.
Closing this.

**Comment by stefanwuthrich** [comment]
@OmkarK45 sorry for the late answer and thank you for posting the workaround.
